name: "Comment on Issue"
run-name: "Comment under an issue"

on:
  issues:
    types: [opened]

concurrency:
  group: comment-${{ github.ref }} # group by branch
  cancel-in-progress: true # cancel older runs

permissions:
  issues: write

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Run Comment Action
        uses: recursivezero/action-club/.github/actions/comment-on-issue@v0.2.58
        with:
          issue_number: ${{ github.event.inputs.issue_number }}
          comment_body: ${{ github.event.inputs.comment_body }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
